title: Meine Website
description: Dokumentation f端r Labor, Maschinenbau & Diplomarbeiten
url: "https://siegikaltmann.github.io"      # <- deinen GitHub-Namen einsetzen
baseurl: "/bookish-guide"                 # <- exakt dein Repo-Name, mit f端hrendem Slash
timezone: Europe/Vienna
markdown: kramdown

search: true
search_full_content: true   # optional: durchsucht den ganzen Inhalt, nicht nur Ausz端ge

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

# --- SEO-Infos ---
logo: /favicon.svg
author: "Siegfried Kaltmann"
github_username: siegikaltmann
# twitter_username: dein_twitter  # falls vorhanden

# Default-OG-Bilder pro Collection (f端r Social Cards)
defaults:
  - scope: { path: "", type: lab }
    values:
      layout: post
      theme: theme-emerald
      image: /assets/cover-lab.jpg
  - scope: { path: "", type: maschinenbau }
    values:
      layout: doc
      theme: theme-violet
      image: /assets/cover-mb.jpg
  - scope: { path: "", type: diplomarbeit }
    values:
      layout: post
      theme: theme-amber
      image: /assets/cover-diplomarbeit.jpg

  
collections:
  lab:
    output: true
    permalink: "/lab/:slug/"
  maschinenbau:
    output: true
    permalink: "/maschinenbau/:slug/"
  diplomarbeit:
    output: true
    permalink: "/diplomarbeit/:slug/"

defaults:
  - scope:
      path: ""
      type: lab
    values:
      layout: post
      theme: theme-emerald
  - scope:
      path: ""
      type: maschinenbau
    values:
      layout: doc
      theme: theme-violet
  - scope:
      path: ""
      type: diplomarbeit
    values:
      layout: post
      theme: theme-amber
